name: amr_pipeline_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - openjdk=11
  - nextflow=23.10.1
  - ncbi-amrfinderplus
  - rgi
  - bowtie2
  - bwa
  - minimap2
  - samtools
  - bcftools
