services:
  postgres:
    image: postgres:16

    container_name: amr_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: amrdb
      POSTGRES_USER: amruser
      POSTGRES_PASSWORD: amrpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: