"""Add virulence_status to sample

Revision ID: 6baba234d086
Revises: add_genome_validation
Create Date: 2026-06-15 07:27:51.997854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6baba234d086'
down_revision: Union[str, Sequence[str], None] = 'add_genome_validation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('batch_name', sa.String(), nullable=True),
    sa.Column('run_cohort_analysis', sa.Boolean(), nullable=True),
    sa.Column('total_isolates', sa.Integer(), nullable=True),
    sa.Column('completed_isolates', sa.Integer(), nullable=True),
    sa.Column('failed_isolates', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cohort_analysis_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_project_id'), 'batches', ['project_id'], unique=False)
    op.create_table('cohort_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=True),
    sa.Column('result_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_results_analysis_type'), 'cohort_results', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_cohort_results_batch_id'), 'cohort_results', ['batch_id'], unique=False)
    op.create_index(op.f('ix_cohort_results_id'), 'cohort_results', ['id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('cap_applied', sa.Boolean(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('weighted', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_confidence_scores_job', 'confidence_scores', ['job_id'], unique=False)
    op.create_index('idx_confidence_scores_sample', 'confidence_scores', ['sample_id'], unique=False)
    op.create_index('idx_confidence_scores_target', 'confidence_scores', ['target_name'], unique=False)
    op.create_table('phenotype_predictions',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('drug', sa.String(length=200), nullable=False),
    sa.Column('drug_class', sa.String(length=200), nullable=True),
    sa.Column('predicted_sir', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('confidence_tier', sa.String(length=50), nullable=True),
    sa.Column('breakpoint_source', sa.String(length=100), nullable=True),
    sa.Column('breakpoint_version', sa.String(length=100), nullable=True),
    sa.Column('is_not_testable', sa.Boolean(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('supporting_genes', sa.JSON(), nullable=False),
    sa.Column('supporting_mutations', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phenotype_preds_drug', 'phenotype_predictions', ['drug'], unique=False)
    op.create_index('idx_phenotype_preds_job', 'phenotype_predictions', ['job_id'], unique=False)
    op.create_index('idx_phenotype_preds_sample', 'phenotype_predictions', ['sample_id'], unique=False)
    op.create_table('resistance_mutations',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('gene_name', sa.String(length=200), nullable=False),
    sa.Column('mutation', sa.String(length=100), nullable=False),
    sa.Column('mechanism', sa.String(length=200), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('identity_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('coverage_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('database_source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resistance_mutations_gene', 'resistance_mutations', ['gene_name'], unique=False)
    op.create_index('idx_resistance_mutations_job', 'resistance_mutations', ['job_id'], unique=False)
    op.create_index('idx_resistance_mutations_sample', 'resistance_mutations', ['sample_id'], unique=False)
    op.create_table('virulence_genes',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('gene_name', sa.String(length=200), nullable=False),
    sa.Column('virulence_factor', sa.String(length=200), nullable=True),
    sa.Column('mechanism', sa.String(length=200), nullable=True),
    sa.Column('contig_id', sa.String(length=200), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('identity_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('coverage_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('database_source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_virulence_genes_job', 'virulence_genes', ['job_id'], unique=False)
    op.create_index('idx_virulence_genes_name', 'virulence_genes', ['gene_name'], unique=False)
    op.create_index('idx_virulence_genes_sample', 'virulence_genes', ['sample_id'], unique=False)
    op.add_column('samples', sa.Column('virulence_status', sa.String(length=30), server_default='not_run', nullable=False))
    op.add_column('samples', sa.Column('batch_id', sa.String(length=36), nullable=True))
    op.add_column('samples', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'samples', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'project_id')
    op.drop_column('samples', 'batch_id')
    op.drop_column('samples', 'virulence_status')
    op.drop_index('idx_virulence_genes_sample', table_name='virulence_genes')
    op.drop_index('idx_virulence_genes_name', table_name='virulence_genes')
    op.drop_index('idx_virulence_genes_job', table_name='virulence_genes')
    op.drop_table('virulence_genes')
    op.drop_index('idx_resistance_mutations_sample', table_name='resistance_mutations')
    op.drop_index('idx_resistance_mutations_job', table_name='resistance_mutations')
    op.drop_index('idx_resistance_mutations_gene', table_name='resistance_mutations')
    op.drop_table('resistance_mutations')
    op.drop_index('idx_phenotype_preds_sample', table_name='phenotype_predictions')
    op.drop_index('idx_phenotype_preds_job', table_name='phenotype_predictions')
    op.drop_index('idx_phenotype_preds_drug', table_name='phenotype_predictions')
    op.drop_table('phenotype_predictions')
    op.drop_index('idx_confidence_scores_target', table_name='confidence_scores')
    op.drop_index('idx_confidence_scores_sample', table_name='confidence_scores')
    op.drop_index('idx_confidence_scores_job', table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index(op.f('ix_cohort_results_id'), table_name='cohort_results')
    op.drop_index(op.f('ix_cohort_results_batch_id'), table_name='cohort_results')
    op.drop_index(op.f('ix_cohort_results_analysis_type'), table_name='cohort_results')
    op.drop_table('cohort_results')
    op.drop_index(op.f('ix_batches_project_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
