"""initial schema

Revision ID: 80cff0f3dfab
Revises: 
Create Date: 2026-06-05 10:48:07.004877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cff0f3dfab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('isolate_name', sa.String(length=200), nullable=False),
    sa.Column('species', sa.String(length=200), nullable=True),
    sa.Column('species_taxid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='UPLOADED', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_samples_species', 'samples', ['species'], unique=False)
    op.create_index('idx_samples_status', 'samples', ['status'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='QUEUED', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_jobs_sample', 'analysis_jobs', ['sample_id'], unique=False)
    op.create_index('idx_analysis_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.create_table('sample_files',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sample_files_sample', 'sample_files', ['sample_id'], unique=False)
    op.create_table('amr_genes',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('gene_name', sa.String(length=200), nullable=False),
    sa.Column('gene_family', sa.String(length=200), nullable=True),
    sa.Column('antibiotic_class', sa.String(length=200), nullable=True),
    sa.Column('resistance_mechanism', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_amr_genes_gene_name', 'amr_genes', ['gene_name'], unique=False)
    op.create_index('idx_amr_genes_job', 'amr_genes', ['job_id'], unique=False)
    op.create_index('idx_amr_genes_sample', 'amr_genes', ['sample_id'], unique=False)
    op.create_table('amr_hits',
    sa.Column('amr_gene_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('identity', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('bit_score', sa.Float(), nullable=True),
    sa.Column('evalue', sa.Float(), nullable=True),
    sa.Column('prediction', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amr_gene_id'], ['amr_genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_amr_hits_gene', 'amr_hits', ['amr_gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_amr_hits_gene', table_name='amr_hits')
    op.drop_table('amr_hits')
    op.drop_index('idx_amr_genes_sample', table_name='amr_genes')
    op.drop_index('idx_amr_genes_job', table_name='amr_genes')
    op.drop_index('idx_amr_genes_gene_name', table_name='amr_genes')
    op.drop_table('amr_genes')
    op.drop_index('idx_sample_files_sample', table_name='sample_files')
    op.drop_table('sample_files')
    op.drop_index('idx_analysis_jobs_status', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_sample', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('idx_samples_status', table_name='samples')
    op.drop_index('idx_samples_species', table_name='samples')
    op.drop_table('samples')
    # ### end Alembic commands ###
