"""Initial schema

Revision ID: 61d7e7b7235a
Revises: 
Create Date: 2026-06-10 14:57:27.482464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '61d7e7b7235a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_databases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=30), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('database_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['db_id'], ['reference_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('isolate_name', sa.String(length=200), nullable=False),
    sa.Column('species', sa.String(length=200), nullable=True),
    sa.Column('species_taxid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('submitter_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_config', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('upload_status', sa.String(length=30), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'file_type', name='uq_sample_file_type')
    )
    op.create_table('sample_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'key', name='uq_sample_meta')
    )
    op.create_table('amr_genes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('db_version_id', sa.Uuid(), nullable=False),
    sa.Column('gene_name', sa.String(length=200), nullable=False),
    sa.Column('gene_family', sa.String(length=200), nullable=True),
    sa.Column('aro_accession', sa.String(length=50), nullable=True),
    sa.Column('drug_class', sa.String(length=200), nullable=True),
    sa.Column('resistance_mechanism', sa.String(length=100), nullable=True),
    sa.Column('antibiotic_class', sa.String(length=200), nullable=True),
    sa.Column('mechanism_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_tier', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['db_version_id'], ['database_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assemblies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('assembly_version', sa.String(length=20), nullable=True),
    sa.Column('assembler', sa.String(length=100), nullable=True),
    sa.Column('assembler_version', sa.String(length=30), nullable=True),
    sa.Column('input_file_id', sa.Uuid(), nullable=True),
    sa.Column('validated_fasta_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['input_file_id'], ['sample_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'assembly_version', name='uq_assembly_sample')
    )
    op.create_table('amr_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amr_gene_id', sa.Uuid(), nullable=False),
    sa.Column('annotation_source', sa.String(length=50), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['amr_gene_id'], ['amr_genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amr_gene_id', 'annotation_source', 'key', name='uq_amr_annotation')
    )
    op.create_table('amr_hits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amr_gene_id', sa.Uuid(), nullable=False),
    sa.Column('detection_tool', sa.String(length=50), nullable=False),
    sa.Column('hit_category', sa.String(length=20), nullable=False),
    sa.Column('identity_pct', sa.Float(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('contig_id', sa.String(length=200), nullable=True),
    sa.Column('contig_start', sa.Integer(), nullable=True),
    sa.Column('contig_end', sa.Integer(), nullable=True),
    sa.Column('strand', sa.String(length=1), nullable=True),
    sa.Column('reference_length', sa.Integer(), nullable=True),
    sa.Column('query_length', sa.Integer(), nullable=True),
    sa.Column('partial_hit', sa.Boolean(), nullable=False),
    sa.Column('raw_result_json', sqlite.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amr_gene_id'], ['amr_genes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assembly_id', sa.Uuid(), nullable=False),
    sa.Column('total_length_bp', sa.BigInteger(), nullable=True),
    sa.Column('contig_count', sa.Integer(), nullable=True),
    sa.Column('n50_bp', sa.Integer(), nullable=True),
    sa.Column('n90_bp', sa.Integer(), nullable=True),
    sa.Column('gc_percent', sa.Float(), nullable=True),
    sa.Column('n_percent', sa.Float(), nullable=True),
    sa.Column('longest_contig', sa.Integer(), nullable=True),
    sa.Column('shortest_contig', sa.Integer(), nullable=True),
    sa.Column('l50', sa.Integer(), nullable=True),
    sa.Column('species_prediction', sa.String(length=200), nullable=True),
    sa.Column('species_confidence', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_warnings', sqlite.JSON(), nullable=True),
    sa.Column('validation_errors', sqlite.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assembly_metrics')
    op.drop_table('amr_hits')
    op.drop_table('amr_annotations')
    op.drop_table('assemblies')
    op.drop_table('amr_genes')
    op.drop_table('sample_metadata')
    op.drop_table('sample_files')
    op.drop_table('analysis_jobs')
    op.drop_table('samples')
    op.drop_table('projects')
    op.drop_table('database_versions')
    op.drop_table('users')
    op.drop_table('reference_databases')
    # ### end Alembic commands ###
