import React, { useState } from "react";

import PipelineTracker from './components/dashboard/PipelineTracker';
import Service1Validation from './components/dashboard/Service1Validation';
import Service3Detection from './components/dashboard/Service3Detection';
import Service4Mutation from './components/dashboard/Service4Mutation';
import Service5Mechanism from './components/dashboard/Service5Mechanism';
import Service6Phenotype from './components/dashboard/Service6Phenotype';
import Service7Virulence from './components/dashboard/Service7Virulence';
import Service8Confidence from './components/dashboard/Service8Confidence';
import GenomicSummary from './components/dashboard/GenomicSummary';
import CohortViews from './components/dashboard/CohortViews';

const FONT = "system-ui, -apple-system, sans-serif";

const TABS = [
  { id: "operations", label: "Pipeline Operations", icon: "⏱" },
  { id: "validation", label: "Genome Validation", icon: "✓" },
  { id: "detection", label: "AMR Detection", icon: "🧬" },
  { id: "mutation", label: "Mutation Profiling", icon: "⚡" },
  { id: "mechanism", label: "Mechanism Classifier", icon: "⚙" },
  { id: "phenotype", label: "Phenotype Prediction", icon: "💊" },
  { id: "virulence", label: "Virulence Factors", icon: "☣" },
  { id: "confidence", label: "Confidence Scoring", icon: "📊" },
  { id: "summary", label: "Genomic Summary", icon: "🎯" },
  { id: "cohort", label: "Cohort Analytics", icon: "🌐" },
];

export default function TBioDashboard() {
  const [tab, setTab] = useState("validation");

  return (
    <div style={{ display: "flex", minHeight: "100vh", fontFamily: FONT, background: "#F9FAFB" }}>
      {/* Sidebar */}
      <div style={{ width: 240, background: "#111827", padding: "20px 0", flexShrink: 0, display: "flex", flexDirection: "column", height: "100vh", position: "sticky", top: 0 }}>
        <div style={{ padding: "0 16px 20px", borderBottom: "1px solid #1F2937" }}>
          <div style={{ fontSize: 16, fontWeight: 800, color: "#FFF", letterSpacing: "-0.02em" }}>AMR Command Center</div>
          <div style={{ fontSize: 10, color: "#6B7280", marginTop: 2, textTransform: "uppercase", letterSpacing: "0.08em" }}>Full Pipeline View</div>
        </div>
        <div style={{ padding: "12px 8px", flex: 1, overflowY: "auto" }}>
          {TABS.map(t => (
            <button key={t.id} onClick={() => setTab(t.id)} style={{
              width: "100%", padding: "12px 12px", border: "none", borderRadius: 6, fontSize: 13,
              cursor: "pointer", display: "flex", alignItems: "center", gap: 10, marginBottom: 4,
              background: tab === t.id ? "#1F2937" : "transparent",
              color: tab === t.id ? "#FFF" : "#9CA3AF", fontWeight: tab === t.id ? 600 : 400,
              fontFamily: FONT, transition: "all 0.15s",
              textAlign: "left"
            }}>
              <span style={{ fontSize: 16, width: 24, textAlign: "center" }}>{t.icon}</span>
              {t.label}
            </button>
          ))}
        </div>
        <div style={{ padding: "12px 16px", borderTop: "1px solid #1F2937" }}>
          <div style={{ fontSize: 8, color: "#4B5563", textTransform: "uppercase", letterSpacing: "0.1em" }}>Pipeline v3.0</div>
          <div style={{ fontSize: 8, color: "#4B5563" }}>9 Microservices Active</div>
        </div>
      </div>

      {/* Main Content */}
      <div style={{ flex: 1, padding: 24, overflowY: "auto", maxWidth: 1200 }}>
        <div style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: 24, fontWeight: 800, color: "#111827", margin: 0 }}>
            {TABS.find(t => t.id === tab)?.label}
          </h1>
          <p style={{ fontSize: 13, color: "#6B7280", margin: "4px 0 0" }}>
            Comprehensive analytics generated by the automated pipeline services.
          </p>
        </div>

        {/* Dynamic Component Rendering based on Tab */}
        <div className="bg-white rounded-xl shadow-sm border border-surface-dark overflow-hidden min-h-[600px]">
          {tab === "operations" && <PipelineTracker />}
          {tab === "validation" && <Service1Validation />}
          {tab === "detection" && <Service3Detection />}
          {tab === "mutation" && <Service4Mutation />}
          {tab === "mechanism" && <Service5Mechanism />}
          {tab === "phenotype" && <Service6Phenotype />}
          {tab === "virulence" && <Service7Virulence />}
          {tab === "confidence" && <Service8Confidence />}
          {tab === "summary" && <GenomicSummary />}
          {tab === "cohort" && <CohortViews />}
        </div>
      </div>
    </div>
  );
}
